"""Web ground station: Flask JSON API + single-page Leaflet map.

Degrades gracefully with no internet: the map tiles simply fail to load and
the page falls back to a plain coordinate readout + track list.

Also serves a post-flight viewer for recorded ground-station sessions:
    /flights                    list recorded gs_logs/<ts> sessions
    /flights/<name>             the flight viewer (shared HTML, see below)
    /flights/<name>/telemetry.csv   raw session CSV
    /flights/list.json          session names for the viewer dropdown
The viewer page is the same self-contained canvas page the flight computer
embeds (src/web/flight_page.cpp); this package carries a mirrored copy in
_flight_viewer.html, regenerated by groundstation/tools/sync_viewer.py.
"""

import html
import json
import os
import pathlib
import threading

from flask import Flask, Response, abort

_LIVE_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Firelink Ground Station</title>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<style>
  body { margin: 0; font-family: -apple-system, sans-serif; background: #0d1117; color: #e6edf3; }
  #map { position: absolute; inset: 0; background: #0d1117; }
  #hud { position: absolute; top: 10px; left: 10px; z-index: 1000;
         background: rgba(13,17,23,.88); border: 1px solid #30363d;
         border-radius: 10px; padding: 10px 14px; font-size: 13px; min-width: 240px; }
  #hud .state { font-weight: 800; font-size: 15px; }
  #hud .mono { font-family: ui-monospace, Menlo, monospace; }
  #hud table td { padding: 1px 6px 1px 0; }
  .st-ARMED { color: #f85149; } .st-PREFLIGHT { color: #58a6ff; }
  .st-LANDED { color: #3fb950; } .st-BOOT { color: #8b949e; }
  #hud a { color: #58a6ff; text-decoration: none; }
  #flights { position: absolute; bottom: 12px; right: 12px; z-index: 1000;
             background: rgba(13,17,23,.88); border: 1px solid #30363d;
             border-radius: 10px; padding: 8px 12px; font-size: 13px; }
</style>
</head>
<body>
<div id="map"></div>
<div id="hud">
  <div class="state st-BOOT" id="state">-</div>
  <table class="mono">
    <tr><td>latitude</td><td id="lat">-</td></tr>
    <tr><td>longitude</td><td id="lon">-</td></tr>
    <tr><td>gps alt</td><td id="galt">-</td></tr>
    <tr><td>baro alt</td><td id="balt">-</td></tr>
    <tr><td>max alt</td><td id="malt">-</td></tr>
    <tr><td>sats</td><td id="sats">-</td></tr>
    <tr><td>packets</td><td id="pkts">-</td></tr>
    <tr><td>last rx</td><td id="age">-</td></tr>
    <tr><td>geiger</td><td id="cpm">-</td></tr>
    <tr><td></td><td><a id="gmaps" target="_blank" href="#">open in maps</a></td></tr>
  </table>
</div>
<div id="flights"><a href="/flights">&#128230; recorded flights</a></div>
<script>
const map = L.map('map', {attributionControl: false}).setView([55, -3], 6);
let online = true;
try {
  L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {maxZoom: 19})
    .addTo(map);
} catch (e) { online = false; }
const track = L.polyline([], {color: '#f85149'}).addTo(map);
const marker = L.circleMarker([0, 0], {radius: 6, color: '#3fb950'}).addTo(map);
let seenFirstFix = false;

async function poll() {
  let j;
  try { j = await (await fetch('/api/live')).json(); } catch (e) { return; }
  const t = j.latest || {};
  const st = document.getElementById('state');
  st.textContent = t.state_name || 'no link';
  st.className = 'state st-' + (t.state_name || 'BOOT');
  document.getElementById('lat').textContent = (t.lat ?? 0).toFixed(6);
  document.getElementById('lon').textContent = (t.lon ?? 0).toFixed(6);
  document.getElementById('galt').textContent = (t.gps_alt_m ?? 0) + ' m';
  document.getElementById('balt').textContent = (t.baro_alt_rel_m ?? 0) + ' m';
  document.getElementById('malt').textContent = (j.max_alt ?? 0).toFixed(0) + ' m';
  document.getElementById('sats').textContent = t.sats ?? 0;
  document.getElementById('pkts').textContent =
      j.packets_ok + ' ok, ' + j.packets_lost + ' lost';
  document.getElementById('age').textContent =
      j.latest ? j.rx_age_s.toFixed(1) + ' s ago' : '-';
  document.getElementById('cpm').textContent = (t.geiger_cpm ?? 0) + ' CPM';
  const gm = document.getElementById('gmaps');
  gm.href = 'https://maps.google.com/?q=' + t.lat + ',' + t.lon;

  if (j.track.length > 0) {
    const pts = j.track.map(p => [p[0], p[1]]);
    track.setLatLngs(pts);
    marker.setLatLng(pts[pts.length - 1]);
    if (!seenFirstFix) { map.setView(pts[pts.length - 1], 15); seenFirstFix = true; }
  }
}
setInterval(poll, 1000); poll();
</script>
</body>
</html>
"""

_LIST_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Firelink Ground Station - flights</title>
<style>
  body { font-family: -apple-system, "Segoe UI", Roboto, sans-serif; margin: 0;
         background: #0d1117; color: #e6edf3; }
  header { display: flex; align-items: center; gap: 12px; padding: 12px 18px;
           background: #161b22; border-bottom: 1px solid #30363d; }
  h1 { font-size: 1.15rem; margin: 0; }
  a { color: #58a6ff; }
  main { padding: 14px; max-width: 720px; margin: 0 auto; }
  table { width: 100%; border-collapse: collapse; font-size: 0.9rem; }
  td, th { padding: 6px 8px; text-align: left; border-bottom: 1px solid #21262d; }
  .mono { font-family: ui-monospace, Menlo, monospace; }
</style>
</head>
<body>
<header>
  <h1>FIRELINK GS <span style="color:#8b949e">/ recorded flights</span></h1>
  <a href="/">&#8592; live map</a>
</header>
<main>
  <table>
    <tr><th>Session</th><th>Size</th><th></th></tr>
    {rows}
  </table>
</main>
</body>
</html>
"""

_VIEWER = None


def _viewer_html():
    global _VIEWER
    if _VIEWER is None:
        path = pathlib.Path(__file__).with_name("_flight_viewer.html")
        _VIEWER = path.read_text(encoding="utf-8")
    return _VIEWER


def _scan_sessions(log_root):
    """Return [(name, csv_abs_path, size)] for recorded sessions."""
    if not log_root or not os.path.isdir(log_root):
        return []
    out = []
    for name in sorted(os.listdir(log_root), reverse=True):
        csv = os.path.join(log_root, name, "telemetry.csv")
        if os.path.isfile(csv):
            out.append((name, csv, os.path.getsize(csv)))
    return out


def create_app(store, log_root="gs_logs"):
    app = Flask(__name__)

    @app.get("/")
    def index():
        return Response(_LIVE_HTML, mimetype="text/html")

    @app.get("/api/live")
    def live():
        snap = store.snapshot()
        body = {
            "latest": snap["latest"],
            "rx_age_s": snap["rx_age_s"],
            "packets_ok": snap["packets_ok"],
            "packets_bad": snap["packets_bad"],
            "packets_lost": snap["packets_lost"],
            "rssi_dbm": snap["rssi_dbm"],
            "max_alt": snap["max_alt"],
            "track": [list(p[:3]) for p in snap["track"]],
            "events": [list(e) for e in snap["events"][-20:]],
        }
        return Response(json.dumps(body), mimetype="application/json")

    @app.get("/flights")
    def flights_list():
        rows = []
        for name, csv, size in _scan_sessions(log_root):
            rows.append(
                f"<tr><td class=\"mono\"><a href=\"/flights/{html.escape(name)}\">"
                f"{html.escape(name)}</a></td>"
                f"<td>{size/1024:.0f} KB</td>"
                f"<td><a href=\"/flights/{html.escape(name)}/telemetry.csv\">csv</a></td></tr>")
        content = _LIST_HTML.replace(
            "{rows}",
            "\n".join(rows) or '<tr><td colspan="3">No recorded sessions yet.</td></tr>')
        return Response(content, mimetype="text/html")

    @app.get("/flights/list.json")
    def flights_json():
        return Response(
            json.dumps({"sessions": [{"name": n} for n, _, _ in _scan_sessions(log_root)]}),
            mimetype="application/json")

    @app.get("/flights/<name>/telemetry.csv")
    def flight_csv(name):
        csv = os.path.join(log_root, name, "telemetry.csv")
        real = os.path.realpath(csv)
        root = os.path.realpath(log_root)
        if not real.startswith(root + os.sep) or not os.path.isfile(real):
            abort(404)
        return Response(open(real, "rb").read(), mimetype="text/csv")

    @app.get("/flights/<name>")
    def flight_viewer(name):
        if not any(n == name for n, _, _ in _scan_sessions(log_root)):
            abort(404)
        return Response(_viewer_html(), mimetype="text/html")

    return app


def run_web(store, host="127.0.0.1", port=8080, log_root="gs_logs"):
    """Start the web server in a daemon thread."""
    app = create_app(store, log_root=log_root)

    def serve():
        app.run(host=host, port=port, threaded=True, use_reloader=False)

    threading.Thread(target=serve, daemon=True).start()
    return port
